# languages.py

TRANS = {
    "KR": {
        "title": "🐣 코버디",
        "subtitle": "초보 개발자의 성장 단짝",
        "login_tab": "🔒 로그인",
        "signup_tab": "✨ 회원가입",
        "google_tab": "🚀 구글로 시작",
        "nickname": "닉네임",
        "password": "비밀번호",
        "login_btn": "로그인",
        "signup_btn": "가입하기",
        "google_btn": "Google 계정으로 로그인",
        "welcome": "반가워요!",
        "api_setup": "🔑 API 설정",
        "api_no_key": "키가 없으신가요?",
        "api_make_here": "여기서 만드세요.",
        "api_placeholder": "Gemini API Key 입력",
        "api_success": "✅ API 키 적용 완료 (AI 사용 가능)",
        "api_info": "💡 키를 입력하지 않으면 시스템 기본 설정을 사용합니다.",
        "pdf_title": "📚 스마트 PDF 학습",
        "pdf_info": "여기에 PDF를 올려주세요. 모든 파일이 누적되어 분석됩니다.",
        "pdf_upload_label": "파일 업로드",
        "pdf_analyzing": "문서를 분석 중입니다...",
        "pdf_done": "학습 완료!",
        "pdf_list": "학습 문서 목록",
        "admin_menu": "👑 관리자 메뉴",
        "admin_view": "대시보드 보기",
        "logout": "🚪 로그아웃",
        "chat_guide_title": "👋 안녕하세요!",
        "chat_guide_desc": "코버디는 여러분의 코딩 학습을 돕는 AI 멘토입니다.",
        "guide_skill": "📚 **스킬 관리**\n\n`파이썬 5` 처럼 입력하여 내 실력을 기록하세요.",
        "guide_search": "🔍 **자료 추천**\n\n`자바 프로젝트 추천해줘` 라고 물어보세요.",
        "guide_doc": "📄 **문서 질문**\n\n왼쪽에 PDF를 올리고 내용에 대해 질문하세요.",
        "chat_placeholder": "무엇이든 물어보세요!",
        "ai_thinking": "코버디가 생각 중... 🐣",
        "ai_searching": "🔍 최신 정보를 수집하고 있어요...",
        "ai_reading": "📄 문서를 꼼꼼히 읽고 있어요...",
        "prompt_lang": "Korean",
        "err_info": "정보가 일치하지 않아요.",
        "err_len": "길이가 부족해요.",
        "success_signup": "가입 완료! 로그인 탭으로 가주세요.",
        "secrets_needed": "Secrets 설정이 필요합니다.",
        "invalid_input": "⚠️ 잘못된 입력입니다.",
        "save_skill": "✅ **{s}** (Level {l}) 저장 완료! 성장하는 모습이 보기 좋아요.",
        # --- 상태 메시지 ---
        "status_thinking": "잠시만요, 요청하신 내용을 확인하고 있어요... 🤔",
        "status_db_checking": "데이터베이스에서 정보를 찾는 중입니다... 🗄️",
        "status_skill_saving": "새로운 성취를 기록하고 있습니다! ✨",
        "status_skill_loading": "보유하신 스킬 목록을 불러오고 있어요... 📚",
        "status_ai_calling": "AI 멘토와 대화 내용을 정리하고 있습니다... 🐣",
        "status_searching": "전 세계의 유익한 자료들을 찾아보고 있어요... 🔍",
        "status_reading": "업로드해주신 문서를 꼼꼼히 읽고 답변을 준비 중이에요... 📄",
        "api_limit_reached": "⚠️ 시스템 API 할당량이 초과되었습니다! 계속 대화하시려면 [API 설정]에서 본인의 키를 입력해주세요.",
        "status_done": "완료! ✨"
    },
    "EN": {
        "title": "🐣 CoBuddy",
        "subtitle": "Your Coding Growth Partner",
        "login_tab": "🔒 Login",
        "signup_tab": "✨ Sign Up",
        "google_tab": "🚀 Google Login",
        "nickname": "Nickname",
        "password": "Password",
        "login_btn": "Login",
        "signup_btn": "Sign Up",
        "google_btn": "Login with Google",
        "welcome": "Welcome!",
        "api_setup": "🔑 API Setup",
        "api_no_key": "No API Key?",
        "api_make_here": "Get one here.",
        "api_placeholder": "Enter Gemini API Key",
        "api_success": "✅ API Key Applied (Ready)",
        "api_info": "💡 Using system default key if empty.",
        "pdf_title": "📚 Smart PDF Learning",
        "pdf_info": "Upload PDFs here. (Multiple files supported)",
        "pdf_upload_label": "Upload Files",
        "pdf_analyzing": "Analyzing documents...",
        "pdf_done": "Analysis Complete!",
        "pdf_list": "Document List",
        "admin_menu": "👑 Admin Menu",
        "admin_view": "View Dashboard",
        "logout": "🚪 Logout",
        "chat_guide_title": "👋 Hello!",
        "chat_guide_desc": "CoBuddy is your AI mentor for coding.",
        "guide_skill": "📚 **Skill Mgmt**\n\nType `Python 5` to save your skill level.",
        "guide_search": "🔍 **Search**\n\nAsk `Recommend Java projects`.",
        "guide_doc": "📄 **Doc Q&A**\n\nUpload PDF and ask questions about it.",
        "chat_placeholder": "Ask me anything!",
        "ai_thinking": "CoBuddy is thinking... 🐣",
        "ai_searching": "🔍 Searching global communities...",
        "ai_reading": "Reading documents carefully...",
        "prompt_lang": "English",
        "err_info": "Invalid credentials.",
        "err_len": "Input too short.",
        "success_signup": "Signed up! Please login.",
        "secrets_needed": "Secrets configuration needed.",
        "invalid_input": "⚠️ Invalid input.",
        "save_skill": "✅ **{s}** (Level {l}) Saved! Keep growing.",
        "status_done": "Done! ✨",
        "pdf_done": "Analysis Complete!",
        # --- Status Messages ---
        "status_thinking": "Wait a second, checking your request... 🤔",
        "status_db_checking": "Checking information from the database... 🗄️",
        "status_skill_saving": "Recording your new achievement! ✨",
        "status_skill_loading": "Loading your skill list... 📚",
        "status_ai_calling": "Organizing the conversation with the AI mentor... 🐣",
        "status_searching": "Searching for helpful resources worldwide... 🔍",
        "status_reading": "Reading your documents and preparing an answer... 📄",
        "api_limit_reached": "⚠️ System API limit reached! Please enter your own key in [API Setup] to continue."
    }
}
